/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus

extern "C" {
#endif
#undef Main_FOCUS_TRAVERSABLE_UNKNOWN
#define Main_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Main_FOCUS_TRAVERSABLE_DEFAULT
#define Main_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Main_FOCUS_TRAVERSABLE_SET
#define Main_FOCUS_TRAVERSABLE_SET 2L
#undef Main_TOP_ALIGNMENT
#define Main_TOP_ALIGNMENT 0.0f
#undef Main_CENTER_ALIGNMENT
#define Main_CENTER_ALIGNMENT 0.5f
#undef Main_BOTTOM_ALIGNMENT
#define Main_BOTTOM_ALIGNMENT 1.0f
#undef Main_LEFT_ALIGNMENT
#define Main_LEFT_ALIGNMENT 0.0f
#undef Main_RIGHT_ALIGNMENT
#define Main_RIGHT_ALIGNMENT 1.0f
#undef Main_serialVersionUID
#define Main_serialVersionUID -7644114512714619750LL
#undef Main_serialVersionUID
#define Main_serialVersionUID 4613797578919906343LL
#undef Main_INCLUDE_SELF
#define Main_INCLUDE_SELF 1L
#undef Main_SEARCH_HEAVYWEIGHTS
#define Main_SEARCH_HEAVYWEIGHTS 1L
#undef Main_OPENED
#define Main_OPENED 1L
#undef Main_serialVersionUID
#define Main_serialVersionUID 4497834738069338734LL
#undef Main_DEFAULT_CURSOR
#define Main_DEFAULT_CURSOR 0L
#undef Main_CROSSHAIR_CURSOR
#define Main_CROSSHAIR_CURSOR 1L
#undef Main_TEXT_CURSOR
#define Main_TEXT_CURSOR 2L
#undef Main_WAIT_CURSOR
#define Main_WAIT_CURSOR 3L
#undef Main_SW_RESIZE_CURSOR
#define Main_SW_RESIZE_CURSOR 4L
#undef Main_SE_RESIZE_CURSOR
#define Main_SE_RESIZE_CURSOR 5L
#undef Main_NW_RESIZE_CURSOR
#define Main_NW_RESIZE_CURSOR 6L
#undef Main_NE_RESIZE_CURSOR
#define Main_NE_RESIZE_CURSOR 7L
#undef Main_N_RESIZE_CURSOR
#define Main_N_RESIZE_CURSOR 8L
#undef Main_S_RESIZE_CURSOR
#define Main_S_RESIZE_CURSOR 9L
#undef Main_W_RESIZE_CURSOR
#define Main_W_RESIZE_CURSOR 10L
#undef Main_E_RESIZE_CURSOR
#define Main_E_RESIZE_CURSOR 11L
#undef Main_HAND_CURSOR
#define Main_HAND_CURSOR 12L
#undef Main_MOVE_CURSOR
#define Main_MOVE_CURSOR 13L
#undef Main_NORMAL
#define Main_NORMAL 0L
#undef Main_ICONIFIED
#define Main_ICONIFIED 1L
#undef Main_MAXIMIZED_HORIZ
#define Main_MAXIMIZED_HORIZ 2L
#undef Main_MAXIMIZED_VERT
#define Main_MAXIMIZED_VERT 4L
#undef Main_MAXIMIZED_BOTH
#define Main_MAXIMIZED_BOTH 6L
#undef Main_serialVersionUID
#define Main_serialVersionUID 2673458971256075116LL
#undef Main_Rows
#define Main_Rows 6L
#undef Main_Columns
#define Main_Columns 7L
/*
 * Class:     Main
 * Method:    createGame
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Main_createGame
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    getBoard
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_Main_getBoard
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Main
 * Method:    dropToken
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_Main_dropToken
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Main
 * Method:    whoIsWinner
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Main_whoIsWinner
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
